import { Murecho } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/NavBar";

// Use @next/font/google to load Murecho font
const murecho = Murecho({
  subsets: ["latin"],
  weight: ["400", "700"], // Use specific weights as needed
});

export const metadata = {
  title: "share-trip",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${murecho.className} antialiased`}>
        <div>
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
